### ISSUE TITLE
Tambahan translate untuk ekstensi lain

### ISSUE THREAD

**Issue by pxnji** [realodix/flarum-ext-indonesian#37]
Translate untuk 
byōbu by flagrow
polls by reflar
user bio by fof
links by fof
dll.

[fof-user-bio.zip](https://github.com/realodix/flarum-ext-indonesian/files/2815222/fof-user-bio.zip)
[reflar-polls.zip](https://github.com/realodix/flarum-ext-indonesian/files/2825398/reflar-polls.zip)
[flagrow-byobu.zip](https://github.com/realodix/flarum-ext-indonesian/files/2815224/flagrow-byobu.zip)
[fof-links.zip](https://github.com/realodix/flarum-ext-indonesian/files/2815225/fof-links.zip)
[flagrow-upload.zip](https://github.com/realodix/flarum-ext-indonesian/files/2825397/flagrow-upload.zip)
[fof-pages.zip](https://github.com/realodix/flarum-ext-indonesian/files/2818724/fof-pages.zip)
[reflar-level-ranks.zip](https://github.com/realodix/flarum-ext-indonesian/files/2818725/reflar-level-ranks.zip)
[flagrow-split.zip](https://github.com/realodix/flarum-ext-indonesian/files/2818726/flagrow-split.zip)

**Comment by realodix** [comment]
Thx, akan Saya kerjakan secepatnya..
